[package]
name = "yarr"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Real-time operating system targeting RISC-V architecture"
homepage = "https://github.com/jamolnng/yarr"
documentation = "https://github.com/jamolnng/yarr"
repository = "https://github.com/jamolnng/yarr"
readme = "README.md"
keywords = ["risc", "rtos"]
categories = ["embedded", "no-std"]

[dependencies]
riscv = "0.9.0"