[package]
name = "yarr"
version = "0.0.0"
edition = "2021"

[dependencies]
riscv = "0.10.1"
riscv-rt = "0.11.0"
yarr-common = { path = "../yarr-common" }
yarr-riscv = { path = "../yarr-riscv", optional = true }
